# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Patterns' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Patterns

  target 'PatternsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PatternsUITests' do
    # Pods for testing
  end

end
